import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from '../Components/ResponsiveAppBar'
import MainFooter from '../Components/MainFooter'
import MainBody from '../Components/MainBody'
export default function Home() {
  return (
    

    <div className={styles.container}><ResponsiveAppBar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBody/>

      <MainFooter/>
    </div>
  )
}
